[project]
name = "mcp-server"
version = "0.0.1b"
description = "a autoTable mcp server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "autotable",
    "mcp[cli]>=1.6.0",
]

[tool.uv.sources]
autotable = { git = "https://github.com/gouzil/autoTable" }
